db:
  uri: mongodb://127.0.0.1:27017
  database: film_lab2
logic:
  delay_seconds: 1
  timeout_seconds: 30
  retries: 3
  recrawl_seconds: 86400
  continuous: true
  user_agent: FilmSeriesIR/1.0 (educational corpus research)
  crawl_categories: true
sources:
- name: wikipedia
  base_url: https://ru.wikipedia.org
  titles:
  - Матрица (фильм)
  - Интерстеллар
  - Бриллиантовая рука
  - Во все тяжкие
  - Игра престолов (телесериал)
  - Шерлок (телесериал)
  categories:
  - Категория:Фильмы по алфавиту
  - Категория:Телесериалы по алфавиту
- name: wikiquote
  base_url: https://ru.wikiquote.org
  titles:
  - Матрица (фильм)
  - Интерстеллар
  - Бриллиантовая рука
  - Во все тяжкие
  - Игра престолов (телесериал)
  - Шерлок
  categories:
  - Категория:Фильмы по алфавиту
  - Категория:Телесериалы по алфавиту
